[package]
name = "tokio-executor-trait"
version = "2.0.0"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description =  "executor-trait implementation for tokio"
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Keruspe/executor-trait"
homepage = "https://github.com/Keruspe/executor-trait"
documentation = "https://docs.rs/tokio-executor-trait"
keywords = ["async", "await", "future", "executor"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
async-trait = "^0.1.42"

[dependencies.tokio]
version = "^1.0"
default-features = false
features = ["rt-multi-thread"]

[dependencies.executor-trait]
version = "^2.0"
path = ".."
